server {
    listen 8081;
    host 127.0.0.1;
    server_name s1;

    root ./www;
    client_max_body_size 10;

    error_page 400 /errors/400.html;
    error_page 413 /errors/413.html;

    location / {
        methods GET;
        index index.html;
        autoindex off;
    }

    location /api {
        methods GET POST;
        index index.html;
        autoindex off;
    }

    location /admin {
        methods POST DELETE;
        upload_store ./uploads;
        autoindex off;
    }
}

server {
    listen 8082;
    host 127.0.0.1;
    server_name s2;

    root ./www;
    client_max_body_size 1000000;

    error_page 400 /errors/400.html;
    error_page 413 /errors/413.html;

    location / {
        methods GET POST DELETE;
        index index.html;
        autoindex off;
    }

    location /static {
        methods GET;
        index index.html;
        autoindex off;
    }

    location /upload {
        methods POST;
        upload_store ./uploads;
        autoindex off;
    }
}

