server {
    listen 8082;
    host 127.0.0.1;
    server_name test_large_size_only;

    root ./www;
    client_max_body_size 1000000;

    error_page 400 /errors/400.html;
    error_page 413 /errors/413.html;

    location /echo {
        methods GET POST DELETE;
        upload_store ./uploads;
    }
}
