server {
    listen 8082;
    host 127.0.0.1;
    server_name test_large2;

    root ./www;
    client_max_body_size 1000000;

    location /echo {
        methods GET POST DELETE;
        index index.html;
    }
}
