server {
	listen 8080;
	host 127.0.0.1;
	server_name example.com;
	error_page 404 /errors/404.html;
	client_max_body_size 1000000;

	#on ne veut pas pouvoir DELETE index.html
	location / {
		root ./www;
		index index.html;
		methods GET POST;
		autoindex off;
	}

	#dans upload on veut pouvoir faire GET DELETE et POST
	#location dédiée pour les fichiers en dehors du site
	location /upload {
		root ./www/upload;
		methods GET POST DELETE;
		upload_store /var/www/upload;
	}

	#on ne veut pas pouvoir DELETE index.html
	location /cgi-bin {
		root ./www/cgi-bin;
		cgi_pass .php /usr/bin/php-cgi;
		methods GET POST;
	}
}

server {
	listen 8081;
	host 127.0.0.1;
	server_name second.com;

	location / {
		root ./www;
		methods GET;
	}
}